<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class pohonus extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->library('upload');
        $this->load->library('image_lib');
        $this->load->model('Pohon_model');
        $this->load->library('form_validation');
        $this->load->library('templateus');
    }

    public function index()
    {
        $pohon = $this->Pohon_model->get_all();

        $data = array(
            'pohon_data' => $pohon
        );

        //$this->load->view('pohon/pohon_list', $data);
        $this->templateus->display('pohonus/pohon_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Pohon_model->get_by_id($id);
        if ($row) {
            $data = array(
		'idpohon' => $row->idpohon,
		'nmpohonum' => $row->nmpohonum,
		'nmpohonil' => $row->nmpohonil,
		'nmpohonlok' => $row->nmpohonlok,
		'foto' => $row->foto,
		'tinggi' => $row->tinggi,
		'diameter' => $row->diameter,
		'longitude' => $row->longitude,
		'lattitude' => $row->lattitude,
		'wilayah' => $row->wilayah,
		'kelangkaan' => $row->kelangkaan,
		'genus' => $row->genus,
		'morfologi' => $row->morfologi,
		'deskripsi' => $row->deskripsi,
	    );
            //$this->load->view('pohon/pohon_read', $data);
            $this->templateus->display('pohonus/pohon_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pohon'));
        }
    }

    public function excel()
    {
        $this->load->helper('exportexcel');
        $namaFile = "pohon.xls";
        $judul = "pohon";
        $tablehead = 0;
        $tablebody = 1;
        $nourut = 1;
        //penulisan header
        header("Pragma: public");
        header("Expires: 0");
        header("Cache-Control: must-revalidate, post-check=0,pre-check=0");
        header("Content-Type: application/force-download");
        header("Content-Type: application/octet-stream");
        header("Content-Type: application/download");
        header("Content-Disposition: attachment;filename=" . $namaFile . "");
        header("Content-Transfer-Encoding: binary ");

        xlsBOF();

        $kolomhead = 0;
        xlsWriteLabel($tablehead, $kolomhead++, "No");
	xlsWriteLabel($tablehead, $kolomhead++, "Nmpohonum");
	xlsWriteLabel($tablehead, $kolomhead++, "Nmpohonil");
	xlsWriteLabel($tablehead, $kolomhead++, "Nmpohonlok");
	xlsWriteLabel($tablehead, $kolomhead++, "Foto");
	xlsWriteLabel($tablehead, $kolomhead++, "Tinggi");
	xlsWriteLabel($tablehead, $kolomhead++, "Diameter");
	xlsWriteLabel($tablehead, $kolomhead++, "Longitude");
	xlsWriteLabel($tablehead, $kolomhead++, "Lattitude");
	xlsWriteLabel($tablehead, $kolomhead++, "Wilayah");
	xlsWriteLabel($tablehead, $kolomhead++, "Kelangkaan");
	xlsWriteLabel($tablehead, $kolomhead++, "Genus");
	xlsWriteLabel($tablehead, $kolomhead++, "Morfologi");
	xlsWriteLabel($tablehead, $kolomhead++, "Deskripsi");

	foreach ($this->Pohon_model->get_all() as $data) {
            $kolombody = 0;

            //ubah xlsWriteLabel menjadi xlsWriteNumber untuk kolom numeric
            xlsWriteNumber($tablebody, $kolombody++, $nourut);
	    xlsWriteLabel($tablebody, $kolombody++, $data->nmpohonum);
	    xlsWriteLabel($tablebody, $kolombody++, $data->nmpohonil);
	    xlsWriteLabel($tablebody, $kolombody++, $data->nmpohonlok);
	    xlsWriteLabel($tablebody, $kolombody++, $data->foto);
	    xlsWriteNumber($tablebody, $kolombody++, $data->tinggi);
	    xlsWriteNumber($tablebody, $kolombody++, $data->diameter);
	    xlsWriteNumber($tablebody, $kolombody++, $data->longitude);
	    xlsWriteNumber($tablebody, $kolombody++, $data->lattitude);
	    xlsWriteLabel($tablebody, $kolombody++, $data->wilayah);
	    xlsWriteLabel($tablebody, $kolombody++, $data->kelangkaan);
	    xlsWriteLabel($tablebody, $kolombody++, $data->genus);
	    xlsWriteLabel($tablebody, $kolombody++, $data->morfologi);
	    xlsWriteLabel($tablebody, $kolombody++, $data->deskripsi);

	    $tablebody++;
            $nourut++;
        }

        xlsEOF();
        exit();
    }

    public function word()
    {
        header("Content-type: application/vnd.ms-word");
        header("Content-Disposition: attachment;Filename=pohon.doc");

        $data = array(
            'pohon_data' => $this->Pohon_model->get_all(),
            'start' => 0
        );
        
        //$this->load->view('pohon/pohon_doc',$data);
        $this->templateus->display('pohonus/pohon_doc', $data);
    }

}

/* End of file pohon.php */
/* Location: ./application/controllers/pohon.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-06-12 08:24:31 */
/* http://harviacode.com */