<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Admin_model extends CI_Model
{

    public $table = 'admin';
    public $id = 'idadmin';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idadmin', $q);
	$this->db->or_like('nmadmin', $q);
	$this->db->or_like('usernameadmin', $q);
	$this->db->or_like('passwordadmin', $q);
	$this->db->or_like('ttladmin', $q);
	$this->db->or_like('emailadmin', $q);
	$this->db->or_like('telpadmin', $q);
	$this->db->or_like('bioadmin', $q);
	$this->db->or_like('fotoadmin', $q);
	$this->db->or_like('wilayah', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idadmin', $q);
	$this->db->or_like('nmadmin', $q);
	$this->db->or_like('usernameadmin', $q);
	$this->db->or_like('passwordadmin', $q);
	$this->db->or_like('ttladmin', $q);
	$this->db->or_like('emailadmin', $q);
	$this->db->or_like('telpadmin', $q);
	$this->db->or_like('bioadmin', $q);
	$this->db->or_like('fotoadmin', $q);
	$this->db->or_like('wilayah', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file admin_model.php */
/* Location: ./application/models/admin_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-06-12 07:58:02 */
/* http://harviacode.com */