<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Taksonomi_model extends CI_Model
{

    public $table = 'taksonomi';
    public $id = 'idtaksonomi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idtaksonomi', $q);
	$this->db->or_like('kingdom', $q);
	$this->db->or_like('subkingdom', $q);
	$this->db->or_like('superdivisi', $q);
	$this->db->or_like('divisi', $q);
	$this->db->or_like('kelas', $q);
	$this->db->or_like('subkelas', $q);
	$this->db->or_like('ordo', $q);
	$this->db->or_like('famili', $q);
	$this->db->or_like('genus', $q);
	$this->db->or_like('spesies', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idtaksonomi', $q);
	$this->db->or_like('kingdom', $q);
	$this->db->or_like('subkingdom', $q);
	$this->db->or_like('superdivisi', $q);
	$this->db->or_like('divisi', $q);
	$this->db->or_like('kelas', $q);
	$this->db->or_like('subkelas', $q);
	$this->db->or_like('ordo', $q);
	$this->db->or_like('famili', $q);
	$this->db->or_like('genus', $q);
	$this->db->or_like('spesies', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file taksonomi_model.php */
/* Location: ./application/models/taksonomi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-06-12 07:58:02 */
/* http://harviacode.com */